#Import Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
import os

csv_files = [
    f for f in os.listdir('/content')
    if f.endswith('.csv')
]

print(csv_files)

['bengaluru_house_prices.csv']

#Load Datasets

In [3]:
df = pd.read_csv('bengaluru_house_prices.csv')

In [4]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

#Check missing values

In [5]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

#Fill Missing Values

In [6]:
df['bath'] = df['bath'].fillna(df['bath'].median())
df['balcony'] = df['balcony'].fillna(df['balcony'].median())
df['location'] = df['location'].fillna(df['location'].mode()[0])

In [10]:
df = df.drop('society', axis=1)

#Convert Area type into numbers

In [19]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['area_type'] = le.fit_transform(df['area_type'])

#displaying the processed datasets

In [20]:
df.head()

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,0,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,0,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,0,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,0,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,0,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00

#saving the Processed data

In [14]:
df.to_csv("processed_house_price_data.csv", index=False)

print("\nTask Completed Successfully!")

Task Completed Successfully!